name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  # to avoid error "Running xmake as root is extremely dangerous and no longer supported."
  XMAKE_ROOT: y

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev
          actions-cache-folder: .xmake-cache-W${{ steps.cache_key.outputs.key }}

      # Force xmake to a specific folder (for cache)
      - name: Set xmake env
        run: echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/xmake-global" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v3
        
      - name: Install dependencies
        run: |
          sudo apt update
          # this is install only for avoid more than 1h of building 
          sudo apt install -y llvm
          python -m pip install --upgrade pip
          python -m pip install cpplint

      - name: Build Croc
        run: xmake -y

      - name: Run tests
        run: xmake run test

      - name: Linter pass 'cpplint'
        run: >
          cpplint --filter=-whitespace/newline,-whitespace/empty_loop_body,-whitespace/indent,-whitespace/blank_line,-readability/casting,-legal/copyright,-build/include_subdir,-build/header_guard,-readability/braces
          $(git ls-files '*.[ch]')
