name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          sudo apt-get install -y curl clang valgrind
          curl -fsSL https://xmake.io/shget.text | bash
          python -m pip install --upgrade pip
          python -m pip install cpplint

      - name: Linter pass 'cpplint'
        run: >
          cpplint --filter=-whitespace/indent,-whitespace/blank_line,-readability/casting,-legal/copyright,-build/include_subdir,-build/header_guard
          $(git ls-files '*.[ch]')

      - name: Compile
        run: xmake

      - name: Valgrind
        run: valgrind build/*/*/*/*
